version: '3'
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    command: --smallfiles

  jsondiffapi:
    build: .
    image: volmar/jsondiffapi:v1
    command: uwsgi --ini uwsgi.ini
    links:
      - mongodb
    depends_on:
      - mongodb
